lane_width:
  min: 1 # 最小线宽
  max: 5 # 最大线宽
  min_head: 6 # 最小箭头宽度
  max_head: 10 # 最大箭头宽度
font_size:
  flow: 12 # 流量标注字体大小
color:
  flow: 0,0,0 # 流量标注字体颜色
  lane:
    南: '#00B050' # 南向车道线颜色
    北: '#FF0000' # 北向车道线颜色
    西: '#FFC000' # 西向车道线颜色
    东: '#7030A0' # 东向车道线颜色

